/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.usuarios;

/**
 *
 * @author Gateway
 */
public class Store extends javax.swing.JFrame {

     usuarios mod;
    
    
    public Store() {
        initComponents();
    }
public Store(usuarios mod) 
     
     {
         initComponents();
         setLocationRelativeTo(null);
         this.mod=mod;
         lblN.setText(mod.getNombre());
         lblR.setText(mod.getNombre_tipo());
         
         if (mod.getId_tipo() == 1) {
             
             
         }else if(mod.getId_tipo() == 2){
             
             Mpro.setVisible(false);
             smAP.setVisible(false);
             
         }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblR = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mP = new javax.swing.JMenu();
        smAP = new javax.swing.JMenu();
        smMP = new javax.swing.JMenu();
        smCP = new javax.swing.JMenu();
        Mpro = new javax.swing.JMenu();
        smAPro = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mP.setText("´Productos");

        smAP.setText("Agregar Producto");
        mP.add(smAP);

        smMP.setText("Modificar Producto");
        mP.add(smMP);

        smCP.setText("Catalogo de Productos");
        mP.add(smCP);

        jMenuBar1.add(mP);

        Mpro.setText("Proveedores}");

        smAPro.setText("Agregar Proveedor");
        Mpro.add(smAPro);

        jMenuBar1.add(Mpro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mpro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblR;
    private javax.swing.JMenu mP;
    private javax.swing.JMenu smAP;
    private javax.swing.JMenu smAPro;
    private javax.swing.JMenu smCP;
    private javax.swing.JMenu smMP;
    // End of variables declaration//GEN-END:variables
}
